General:
    Modus: "Collider"
    Delta_Time: 0.1
    End_Time: 100.0
    Randomseed: -1
    Nevents: 10000
    Use_Grid: true
    Time_Step_Mode: "Fixed"

Modi:
    Collider:
        Projectile:
            Particles: {2212: 79, 2112: 118}
        Target:
            Particles: {2212: 79, 2112: 118}
        Impact:
            Sample: "quadratic"
            Range: [0.,4.7] # 0. - 4.7 (0-10%), 4.7 - 6.6 (10%-20%), 6.6 - 8.1 (20%-30%), 8.1 - 9.3 (30%-40%) https://inspirehep.net/literature/1644672

        E_Kin: 1.23
        Fermi_Motion: "frozen"
        Calculation_Frame: "fixed target"
        Collisions_Within_Nucleus: False
        Initial_Distance: 4.0

Output:
    Particles:
        Format: ["Oscar2013"]
        Extended: True
        Only_Final: "IfNotEmpty"
